### PR TITLE
Moving person's commmunities to member of property

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Moving from dco:associatedDCOCommunity to the member of faux property

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
Works on local system. Will push to dco.tw.rpi.edu next.

**Comment by mrpatrickwest** [comment]
Works on dco.tw.rpi.edu

**Comment by mrpatrickwest** [comment]
Craig Manning profile in production: https://info.deepcarbon.net/vivo/display/da0842aa0-b55e-4480-982f-1202b71b25f7

Craig Manning profile in test: https://dco.tw.rpi.edu/vivo/individual?uri=http%3A%2F%2Finfo.deepcarbon.net%2Findividual%2Fda0842aa0-b55e-4480-982f-1202b71b25f7

New people browser, search for Manning: https://dco.tw.rpi.edu/vivo/people

**Comment by zhongh** [comment]
On the test server, the "Positions" area in the personal summary panel is not showing. Is it because it is an older version of VIVO?

**Comment by mrpatrickwest** [comment]
Are you logged in or not logged in? Can you give me an example.

**Comment by zhongh** [comment]
On production it displays:
image
But I can't see the "Positions" panel on dco.tw.rpi.edu/vivo (I couldn't log in, that might be the reason?)

**Comment by mrpatrickwest** [comment]
Those were removed as positions because they are communities. It's part of the tickets that I'm working on.. Look at Marshall's or mine to see an example or a position with an organization.

**Comment by zhongh** [comment]
My doubts are figured! Thank you for the patience with my questions! Looks very good ! :+1:

**Pull request merged**
