### PR TITLE
Es datasets ingest script

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Elasticsearch dataset ingest script was missing from the scripts directory. Created it and updated it to specify a mapping file.

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
This is working in production.

**Comment by zednis** [comment]
My preference is to keep the cronjobs separate for the different ingest scripts so that we can run them on different schedules.

**Comment by mrpatrickwest** [comment]
They are separate.

**Comment by zednis** [comment]
Are we using this script anywhere?  My previous comment was about having the separate cronjobs was because I did not see the need for this consolidated job script.

**Comment by mrpatrickwest** [comment]
Not at the moment, but thought I’d keep the script up to date anyway.

**Comment by zednis** [comment]
ah, ok

**Pull request merged**
