### PR TITLE
Datatype browser review

### PR DESCRIPTION
**Pull request by am-e**
Test browser at http://udco.tw.rpi.edu/vivo/datatypes-test 
Recently added Parameters facet and ordered Creation Year descending.

### CODE REVIEW

**Comment by olyerickson** [comment]
The Datatype Browser looks great! I do feel there needs to be some (minor) changes and/or additions to make it appear more relevant to a particular application domain: 
1. Facets (on left) should be ordered by potential relevance to a user. So e.g. "Subject Area," "Parameter" and "Creator" should top the list (probably in that order)
2. A count of the number of registered datasets using the datatype --- "Number of datasets with this type" --- should appear in the results widget listing. 
3. On the Dataset Summary Page, the dataset URI column (ie the VIVO profile URI) could be dropped, and instead the title could be linked using that URI. This will be more visually appealing, instead of cramming long URIs and long titles into a row.

**Comment by am-e** [comment]
1. I have reordered the facets accordingly, I agree that their order is more relevant now.
2. I am looking into the query to count the number of datasets for a given data type.
3. I understand this is in the VIVO data type summary page which is outside the scope of this browser, I'd be happy to work on it on another ticket.

**Comment by zednis** [comment]
@olyerickson Do you feel the browser is ready to be pushed to production?

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
