### PR TITLE
Person browser

### PR DESCRIPTION
**Pull request by zednis**

### CODE REVIEW

**Comment by zednis** [comment]
In test at http://udco.tw.rpi.edu/vivo/people-test

**Comment by zednis** [comment]
updates based on user feedback
- [x] updated checkbox text to "Show only DCO members"
- [x] changed DCO ID badge label to "profile"
- [x] moved dco community property to be above organizations in result records

@mrpatrickwest do you think this pull request is ready to merge?  We can make minor style updates and add the map in follow-up feature branches as necessary.

**Comment by mrpatrickwest** [comment]
:shipit: 

can you go ahead and create the page in production. Don't replace the people page just yet, just create a test page. Then it'll be easy to just switch pages.

But this can be merged into master.

**Comment by zednis** [comment]
https://info.deepcarbon.net/vivo/people-next

We should probably add the notifications at the top.

**Pull request merged**
