### PR TITLE
Added newline to end of bulk file creation for all scripts

### PR DESCRIPTION
**Pull request by am-e**
Added a new line to the bulk file write statement in all ingest scripts.

### CODE REVIEW

**Comment by mrpatrickwest** [comment]
@zednis this was to fix the problem where the datatype documents weren't being pushed to elastic search but if I added a newline at the bottom to the bulk file then it loaded. As far as I could tell there weren't any problems with the others, but may as well make the change to them all.

I don't think we need a \r here, just the \n

**Comment by zednis** [comment]
Ah, that makes sense.  ES expects every object in the bulk ingest to end with a newline.  It probably has been causing us to lose 1 record on each ingest, but the count was so low we never noticed it before.

**Comment by zednis** [comment]
:shipit:

**Comment by mrpatrickwest** [comment]
:shipit:

**Pull request merged**
